### ISSUE TITLE
Пропажа предметов при выдаче

### ISSUE THREAD

**Issue by nagibqwe** [kdevmcTeam/KShop#1]
Допустим, если у игрока заполнен инвентарь предметами, то при выдачи с корзины, он пропадает в никуда.

**Comment by nagibqwe** [comment]
```
[20:04:57] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: nagibqwe issued server command: /items
[20:04:57] [Craft Scheduler Thread - 120/WARN] [CatServer]: A Mod/Plugin try to async call InventoryOpenEvent, it will be executed safely on the main server thread until return!
[20:04:57] [Craft Scheduler Thread - 120/WARN] [CatServer]: Please check the stacktrace in debug.log and report the author.
[20:04:57] [Craft Scheduler Thread - 120/DEBUG] [CatServer]: Try to async call InventoryOpenEvent
java.lang.RuntimeException: null
	at catserver.server.CatServer.asyncCatch(CatServer.java:62) ~[CatServer.class:git-CatServer-1.12.2-]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:845) ~[CraftEventFactory.class:git-CatServer-1.12.2-]
	at net.minecraft.entity.player.EntityPlayerMP.func_71007_a(EntityPlayerMP.java:1081) ~[oq.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:221) ~[CraftHumanEntity.class:git-CatServer-1.12.2-]
	at ru.kdev.kshop.gui.api.Gui.<init>(Gui.java:30) ~[?:?]
	at ru.kdev.kshop.gui.ItemsGui.<init>(ItemsGui.java:28) ~[?:?]
	at ru.kdev.kshop.commands.ItemsCommand.lambda$onCommand$0(ItemsCommand.java:26) ~[?:?]
	at ru.kdev.kshop.database.MySQL.lambda$getItems$3(MySQL.java:165) ~[?:?]
	at ru.kdev.kshop.database.MySQL.lambda$executeQuery$1(MySQL.java:99) ~[?:?]
	at ru.kdev.kshop.database.MySQL.lambda$async$0(MySQL.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [CraftTask.class:git-CatServer-1.12.2-]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]``
```
